version: 2
jobs:
  test:
    docker:
      - image: rishabhpoddar/supertokens_laravel_driver_testing
    steps:
      - add_ssh_keys:
          fingerprints:
            - "46:31:70:29:8c:9b:ab:66:b6:7b:fe:42:9f:45:28:90"
      - checkout
      - run: add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
      - run: apt install php7.3-mbstring -y
      - run: composer install
      - run: (cd .circleci/ && ./doTests.sh)
workflows:
  version: 2
  tagged-build:
    jobs:
      - test:
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/