version: 2
jobs:
  test:
    docker:
      - image: rishabhpoddar/supertokens_laravel_driver_testing
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b3:da:ef:15:52:aa:a3:69:c3:6b:14:0c:be:23:b7:c7"
      - checkout
      - run: composer install
      - run: (cd .circleci/ && ./doTests.sh)
workflows:
  version: 2
  tagged-build:
    jobs:
      - test:
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/